# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
encoding: "utf-8"
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: dbyll
duoshuo: xlaoyu
# google_analytics: dbyll

rdiscount:
  extensions: [autolink]

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: xlaoYu's bloggggggggg
      comments: true
      keywords: javascript,web,前端,个人blog

description: Stylish Jekyll Theme
author:
  name: xlaoYu
  email: frank_yll@163.com
  github: Yuliang-Lee
  #twitter: null
  #pinterest: asd123
  #linkedin: asd123
  #rss: false
  bio: 未识乾坤大，但怜草木青
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
